RUN_STRINGS = (
    "Lariii ada wibuuu." "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "Kembali kesini kontolllll!",
    "REEEEEEEEEEEEEEEEEE!!!!!!!",
    "Lari yang jauh gausah kembali, lu gk penting!",
    "Jangan tinggalkan aku sendirian!!",
    "Run run run ada orgil!",
    "Lariiiii ada orang gajelas!",
    "Yare yare linglung",
    "*Naruto run activated*",
    "*Nezuko run activated*",
    "Hei bertanggung jawab atas apa yang baru saja kamu lakukan!",
    "Semoga peluang selalu menguntungkan Anda.",
    "Jalankan semua orang, mereka baru saja menjatuhkan bom 💣💣",
    "Dan mereka menghilang selamanya, tidak pernah terlihat lagi.",
    "Legenda mengatakan, mereka masih berlari.",
    "Hasta la vista, baby.",
    "Ah, sia-sia. Saya suka yang itu.",
    "Lariii aku mau diperkosa ah ah ah!",
)

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

SLAP_FALLEN_TEMPLATES = (
    "Tampar aku sekali lagi dan aku akan membungkammu.",
    "Berhenti menamparku. Atau ku panggilkan @ebnudoang.",
    [
        "Aku membungkammu sebentar.",  # normal reply
        "Berhentilah menamparku hanya karena aku tidak bisa membungkammu. REEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Shut up!",
        "Silence!",
    ],
)

SLAP_TEMPLATES = (
    "{user2} dibunuh oleh sihir.",
    "{user2} mati kelaparan.",
    "{user2} terlempar ke dalam kehampaan oleh {user1}.",
    "{user2} pingsan.",
    "{user2} diperkosa hingga hamil anak kembar oleh {usee1}.",
    "{user2} hamil karena {user1}.",
    "{user2} punya rekt.",
    "{user2} diewe oleh {user1}.",
    "{user2} diiris dan dipotong dadu oleh {user1}.",
    "{user2} bermain kentang panas dengan granat.",
    "{user2} ditusuk oleh {user1}.",
    "{user2} makan granat.",
    "{user2} apa untuk makan malam?!",
    "{user2} diakhiri oleh {user1}.",
    "{user1} meremas kemaluan {user2} hingga crot 3x.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} taruh {user2} di zona pertemanan anjayy sad.",
    "{user1} menampar {user2} dengan pintu!",
    "{user2} dibunuh dan diperkosa oleh {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} dilempari batu ... oleh mo yang marah.",
    "{user1} menggugat celana {user2}.",
    "{user2} adalah satu pukulan KO oleh {user1}.",
    "{user1} mengirimkan {user2} ke rumah sakit.",
    "{user2} adalah sebuah kesalahan. - '{user1}' ",
    "{user2} dibuat berlebihan.",
    "{user1} {hits} {user2} dengan kelelawar!.",
    "{user1} {hits} {user2} dengan Tendangan Taijutsu!.",
    "{user1} {hits} {user2} dengan kondom bekas!.",
    "{user1} {hits} {user2} dengan Pukulan Jet!.",
    "{user1} {hits} {user2} dengan kontol sapi!.",
    "{user1} {hits} {user2} dengan tv!.",
    "{user1} {hits} {user2} dengan sepeda motor!.",
    "{user1} {hits} {user2} dengan Texas Smash!.",
    "{user1} {hits} {user2} dengan California Smash!.",
    "{user1} {hits} {user2} dengan batu!.",
    "{user1} {hits} {user2} bakso!.",
    "{user1} {hits} {user2} dengan Carolina Smash!.",
    "{user1} {hits} {user2} dengan King Kong Gun!.",
    "{user1} {hits} {user2} dengan tongkat baseball - yang terbuat dari logam.!.",
    "*Pukulan serius {user2}*.",
    "*Pukulan biasa {user2}*.",
    "*Pukulan Normal Berturut-turut {user2}*.",
    "*Pukulan Normal Dua Tangan Berturut-turut {user2}*.",
    "*mengabaikan {user2} untuk membiarkan mereka mati karena malu*.",
    "*poin di {user2}* Ada apa dengan lancang... anak hilang ini?.",
    "*Memerkosa {user2} dengan temannya*.",
    "{user1} mencium {user2} di mulut!",
    "{user1} menusuk kemaluan {user2} ahhh",
    "{user1} menusuk perut {user2} dengan pisau!",
    "{user1} menusuk {user2} dengan jarum!",
    "{user1} menusuk {user2} dengan pena!",
    "{user1} menusuk {user2} dengan pistol setrum!",
    "{user2} diam-diam adalah Furry!",
    "Hai semuanya! {user1} memintaku untuk menjadi jahat!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Ambil ini {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Di Sini {user2} pegang ini\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nmatieeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Semprotan serangga {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} kamu hama!",
    "( う-´)づ︻╦‌╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} dengan {item}.",
    "{user1} {hits} {user2} di wajah dengan {item}.",
    "{user1} {hits} {user2} sekitar sedikit dengan {item}.",
    "{user1} {throws} sebuah {item} pada {user2}.",
    "{user1} meraih {item} dan {throws} itu di {user2}.",
    "{user1} meluncurkan sebuah {item} di {user2}'arah umum.",
    "{user1} mulai menampar {user2} konyol dengan {item}.",
    "{user1} pin {user2} ke bawah dan berulang kali {hits} mereka dengan {item}.",
    "{user1} meraih {item} dan {hits} {user2} dengan itu.",
    "{user1} meniduri {user2} di kursi.",
    "{user1} memberikan dorongan ramah untuk membantu {user2} belajar berenang di lava.",
    "{user1} diganggu {user2}.",
    "Nyaam makan {user2}. *nomnomnom*",
    "{user1} {throws} bola master di {user2}, resistensi adalah sia-sia.",
    "{user1} {hits} {user2} dengan sinar aksi...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "WhoPixel will oof {user2} to infinity and beyond.",
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to his home, the planet of the apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "You know what’s worse than Dad jokes? {user2}!",
    "{user1} took all of {user2}'s cookies.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} lost his race piece!",  # No game no life reference
    "Shut up {user2}, you are just {user2}.",  # No game no life reference
    "{user1} hits {user2} with Aka si anse!",  # No game no life reference
    "@NeoTheKitty scratches {user2}",  # Pixels pet cat - @NeoTheKitty
    "Majin buu ate {user2}",  # Dbz
    "Goblin slayer slays {user2}",  # Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    "Oh no! We are all out of pats.",
    "This is a designated no pat zone!",
    "No pats for {user2}!",
    "{user1} spoils {user2} with headpats!",
    "{user2} received one free headpat!",
    "{user1} headpats {user2} whilst giving a lap pillow",
    "{user1} aggressively pats {user2}",
    "{user1} gently strokes {user2}'s head",
    "Pat, pat, pat, pat",
    "{user2} could not escape {user1}'s headpats",
    "{user2}.exe has stopped working",
    "{user1} rubs {user2} on the neck",
    "Must... extort... HEADPATS",
    "{user1} headpats {user2}'s head with a pat",
    "{user1} pats {user2} unexpectedly",
    "{user1} pats {user2} with consent, maybe?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} pats {user2} friendlily",
    "{user2} uses HEADPATS? O KAWAII KOTO",
    "*headpats.gif intensifies for {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = (
    "ɪ ᴀᴍ ᴀʟɪᴠᴇ ʙᴀʙʏ! 🖤",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("Heads", "Tails")

EIGHTBALL = [
    "🟢 As I see it, yes.",
    "🟡 Ask again later.",
    "🟡 Better not tell you now.",
    "🟡 Cannot predict now.",
    "🟡 Concentrate and ask again.",
    "🟡 Don’t count on it.",
    "🟢 It is certain.",
    "🟢 It is decidedly so.",
    "🟢 Most likely.",
    "🔴 My reply is no.",
    "🔴 My sources say no.",
    "🔴 Outlook not so good.",
    "🟢 Outlook good.",
    "🟡 Reply hazy, try again.",
    "🟢 Signs point to yes.",
    "🔴 Very doubtful.",
    "🟢 Without a doubt.",
    "🟢 Yes.",
    "🟢 Yes – definitely.",
    "🟢 You may rely on it.",
]

DECIDE = ("Yes.", "No.", "Maybe.")

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "I ran out of tables, will order more.",
    "Go do some work instead of flippin tables.",
)
