TRUTH = (
    "Have you ghosted someone?" "Have you ever walked in on your parents doing 'it'?",
    "Who was the last person you liked the most? Why?",
    "Have you ever been suspended from school?",
    "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?",
    "What’s the one thing you’re afraid to lose?",
    "Do you like someone as of the moment?",
    "One thing about your best friend you are jealous of?",
    "Would you cheat on your boyfriend for a rich guy?",
    "What is your biggest turn on?",
    "When’s the last time you lied to your parents and why?",
    "Describe your ideal partner.",
    "Do you love @anonymous_was_bot ?",
    "What’s the scariest thing you’ve ever done?",
    "Have you ever picked your nose and eaten it?",
    "When’s the last time you lied to your parents and why?",
    "Have you ever lied about your age to participate in a contest?",
    "Have you ever been caught checking someone out?",
)

DARE = (
    "Tampilkan foto paling memalukan di ponsel Anda",
    "Tunjukkan lima orang terakhir yang Anda chat WhatsApp dan apa isi pesannya",
    "Biarkan anggota grup lainnya DM seseorang dari akun Instagram Anda",
    "Makanlah bawang putih mentah",
    "Lakukan 100 squat",
    "Beri tahu @ebnudoang bahwa kamu mencintainya.",
    "Simpan tiga es batu di mulutmu sampai meleleh",
    "Katakan sesuatu yang kotor kepada orang di sebelah kiri Anda Anda punya teman!",
    "Berikan pijatan kaki kepada orang di sebelah kanan Anda",
    "Masukkan 10 cairan berbeda yang tersedia ke dalam cangkir dan minumlah",
    "*Ucapkan kata pertama yang muncul di pikiranmu",
    "Berikan lap dance kepada seseorang pilihan Anda",
    "Lepaskan empat item pakaian",
    "pap tetek",
    "pap kontol",
    "follow ig @ebnu_am minta follback dm atau pc @ebnudoang",
    "Kirim sext ke orang terakhir di buku telepon Anda",
    "Pamerkan wajah orgasme Anda",
    "Menggoda makan pisang",
    "Kosongkan dompet / dompet Anda dan tunjukkan kepada semua orang apa yang ada di dalamnya",
    "Lakukan perayapan seksi terbaikmu",
    "Berpura-pura menjadi orang di sebelah kanan Anda selama 10 menit",
    "coli",
    "subs @katakatauntukmu @katakatasadardiri @keluhkesahkehidupankita @anythinghoneyy",
    "colmek",
    "join @mutualaninstagram2022_ID" biar jadi seleb",
    "Cobalah untuk memasukkan seluruh kepalan tangan Anda ke dalam mulut Anda",
    "Ceritakan kepada semua orang kisah memalukan tentang dirimu sendiri",
    "Coba jilat sikumu",
    "Posting selfie tertua di ponsel Anda di Instagram Stories",
    "Ceritakan kisah paling menyedihkan yang kamu tahu",
    "Culik 20 orang kedalam group @asaboopride",
    "Menari tanpa musik selama dua menit",
    "Tarian tiang dengan tiang imajiner",
    "Biarkan orang lain menggelitikmu dan mencoba untuk tidak tertawa",
    "Masukkan camilan ke dalam mulut Anda sekaligus sebanyak yang Anda bisa",
    "Kirim 'aku sayang kamu' ke orang random dalam 1 group harus lawan jenis.",
    "Kirim selfie terjelekmu.",
    "Kirim tangkapan layar riwayat pencarian facebook Anda",
    "Kirim tangkapan layar galeri Anda.",
    "Kirim tangkapan layar kotak masuk messenger Anda",
    "Katakan sesuatu yang sangat intim.",
    "Kirim tangkapan layar kotak masuk twitter Anda",
    "Kirim tangkapan layar layar beranda Anda.",
    "Kirim cover lagu favoritmu. 🎤",
    "Lakukan lelucon lirik pada seseorang dan kirimkan buktinya.",
    "Mengakui crus Anda saat inih. ❤️",
    "Nyatakan siapa cinta sejatimu.",
    "Kirim tangkapan layar galeri Anda.",
    "Jadikan foto gebetanmu sebagai dp.",
    "Sarankan saya lebih berani.",
    "Lakukan tarian ayam terbaik Anda di luar di halaman.",
    "Gali lubang di halaman dengan satu tangan.",
    "Letakkan es batu di baju Anda.",
    "Mulailah menjilat hidung Anda.",
    "Letakkan pakaian Anda ke belakang.",
    "Lakukan twerk selama semenit sementara teman Anda merekamnya.",
    "Teks seseorang hanya menggunakan hidung Anda.",
    "Lakukan 20 jungkir balik.",
    "Pergi ke luar dan berteriak, 'Aku mengambil hidungku!' kepada orang pertama yang Anda lihat.",
    "Isi sebanyak mungkin marshmallow di mulut Anda.",
    "Makan sesendok sesawi.",
    "Bertingkah seperti anjing.",
    "Selama satu jam berikutnya kenakan kap lampu di kepala Anda sebagai topi.",
    "Lepaskan sabuk Anda sendiri atau celana menggunakan siku Anda.",
    "Tag anggota group yang kamu kangenin",
    "Berjalanlah dengan kaki terikat.",
    "Typing jametzz seharian",
    "Kenakan pakaian yang dipilih oleh teman Anda.",
    "Tahan napas selama 30 detik. Kalo nagih boleh nambah",
    "Pap nenen",
    "Invite anggota keluarga anda ke @asaboopride",
    "Chat orang random anggota group bilang i love you 5000 yang 2000 buat beli siomay",
)
