TRUTH = (
    "Apakah kamu pernah ngentod?",
    "Pernahkah Anda mencuri?",
    "Siapa orang terakhir yang paling kamu sukai? Mengapa?",
    "Apakah Anda pernah diskors dari sekolah?",
    "Kehilangan orang tua apa pacar?",
    "Apa satu hal yang kamu takut kehilangan?",
    "Apakah kamu menyukai seseorang saat ini??",
    "Satu hal tentang sahabatmu yang membuatmu iri?",
    "Apakah Anda akan menipu pacar Anda untuk pria kaya?",
    "Apa giliran terbesarmu?",
    "Kapan terakhir kali kamu berbohong kepada orang tuamu dan alasannya?",
    "Deskripsikan pasangan ideal Anda.",
    "Sudahkah Anda mengikuti ig @ebnu_am? Jika belum follow dong kak, yang cakep difollback",
    "Apa hal paling menakutkan yang pernah kamu lakukan?",
    "Pernahkah Anda mengupil dan memakannya?",
    "Kapan terakhir kali kamu berbohong kepada orang tuamu dan alasannya?",
    "Pernahkah Anda berbohong tentang usia Anda untuk berpartisipasi dalam kontes??",
    "Pernahkah Anda ketahuan sedang memeriksa seseorang?",
    "Lagi sange gak?",
    "Kalo sange ngapain?",
    "Apakah Anda sudah naik kereta?",
    "Apakah Anda lebih suka menjadi putri atau putri duyung?",
    "Apakah Anda sudah berkemah di halaman belakang Anda?",
    "Apa hal paling memalukan yang diketahui orang tua Anda lakukan?",
    "Apakah Anda memiliki bakat khusus?",
    "Apa yang paling memalukan saat Anda kentut?",
    "Pernahkah Anda muntah di mobil seseorang?",
    "Berapa banyak anggota keluarga?",
    "Apakah Anda lebih suka memiliki babi peliharaan atau kambing peliharaan?",
    "Pernahkah Anda mengatakan bahwa Anda selesai makan malam padahal sebenarnya tidak?",
    "Pernahkah Anda mengadu?",
    "Berapa kali Anda melakukan allnighter?",
    "Apa yang terlama yang pernah Anda lakukan tanpa mandi?",
    "Berapa banyak laki-laki / perempuan yang tidur dengan Anda?",
    "Apakah Anda suka menari atau bernyanyi?",
    "Berapa banyak laki-laki / perempuan yang tidur dengan Anda?",
    "Apakah Anda punya ponsel?",
    "Apa posisi seksual favorit Anda?",
    "Sudahkah Anda berpura-pura menjadi pahlawan super?"
    "Apa film yang paling tidak kamu sukai?",
    "Jika Anda memiliki mesin waktu, periode waktu apa yang akan Anda kunjungi?",
    "Berapa banyak anggota keluarga?",
    "Apa yang Anda takutkan?",
    "Apa kartun favorit Anda dari generasi Anda?",
    "Berapa banyak pesta yang telah Anda lakukan di rumah Anda?",
    "Pernahkah Anda tidur dengan seseorang yang berjenis kelamin sama?",
    "Apa yang tidak Anda sukai dari pertemuan keluarga?",
    "Apa yang tidak Anda sukai dari pertemuan keluarga?",
    "Pernahkah Anda tidur dengan seseorang yang berjenis kelamin sama?",
    "Pernahkah kamu bolos sekolah?",
    "Siapa nama orang yang paling Anda benci.",
    "Apa yang ingin Anda lakukan ketika Anda sendirian?",
    "Apa saja cara Anda menipu pada tugas-tugas?",
    "Siapa orang yang berpakaian paling buruk di ruangan ini?",
)

DARE = (
    "Tampilkan foto paling memalukan di ponsel Anda"
    "Tunjukkan lima orang terakhir yang Anda chat WhatsApp dan apa isi pesannya",
    "Biarkan anggota grup lainnya DM seseorang dari akun Instagram Anda",
    "Makanlah bawang putih mentah",
    "Lakukan 100 squat",
    "Beri tahu @ebnudoang bahwa kamu mencintainya.",
    "Simpan tiga es batu di mulutmu sampai meleleh",
    "Katakan sesuatu yang kotor kepada orang di sebelah kiri Anda Anda punya teman!",
    "Berikan pijatan kaki kepada orang di sebelah kanan Anda",
    "Masukkan 10 cairan berbeda yang tersedia ke dalam cangkir dan minumlah",
    "*Ucapkan kata pertama yang muncul di pikiranmu",
    "Berikan lap dance kepada seseorang pilihan Anda",
    "Lepaskan empat item pakaian",
    "pap tetek",
    "pap kontol",
    "follow ig @ebnu_am minta follback dm atau pc @ebnudoang",
    "Kirim sext ke orang terakhir di buku telepon Anda",
    "Pamerkan wajah orgasme Anda",
    "Menggoda makan pisang",
    "Kosongkan dompet / dompet Anda dan tunjukkan kepada semua orang apa yang ada di dalamnya",
    "Lakukan perayapan seksi terbaikmu",
    "Berpura-pura menjadi orang di sebelah kanan Anda selama 10 menit",
    "coli",
    "subs @katakatauntukmu @katakatasadardiri @keluhkesahkehidupankita @anythinghoneyy",
    "colmek",
    "join @mutualaninstagram2022_ID",
    "Cobalah untuk memasukkan seluruh kepalan tangan Anda ke dalam mulut Anda",
    "Ceritakan kepada semua orang kisah memalukan tentang dirimu sendiri",
    "Coba jilat sikumu",
    "Posting selfie tertua di ponsel Anda di Instagram Stories",
    "Ceritakan kisah paling menyedihkan yang kamu tahu",
    "Culik 20 orang kedalam group @asaboopride",
    "Menari tanpa musik selama dua menit",
    "Tarian tiang dengan tiang imajiner",
    "Biarkan orang lain menggelitikmu dan mencoba untuk tidak tertawa",
    "Masukkan camilan ke dalam mulut Anda sekaligus sebanyak yang Anda bisa",
    "Kirim 'aku sayang kamu' ke orang random dalam 1 group (harus lawan jenis).",
    "Kirim selfie terjelekmu.",
    "Kirim tangkapan layar riwayat pencarian facebook Anda",
    "Kirim tangkapan layar galeri Anda.",
    "Kirim tangkapan layar kotak masuk messenger Anda",
    "Katakan sesuatu yang sangat intim.",
    "Kirim tangkapan layar kotak masuk twitter Anda",
    "Kirim tangkapan layar layar beranda Anda.",
    "Kirim cover lagu favoritmu. 🎤",
    "Lakukan lelucon lirik pada seseorang dan kirimkan buktinya.",
    "Mengakui crus Anda saat inih. ❤️",
    "Nyatakan siapa cinta sejatimu.",
    "Kirim tangkapan layar galeri Anda.",
    "Jadikan foto gebetanmu sebagai dp.",
    "Sarankan saya lebih berani.",
)
